### ISSUE TITLE
How to create an "Appender" for remote services?

### ISSUE THREAD

**Issue by marcellodesales** [timboudreau/bunyan-java#1]
Hi there,

I'm coming from Node.js and I need to provide a Java implementation for logging. How can I specify an "Appender" for the output provided by Bunyan-java?

For instance, we use the service "LogEntries" to publish our logs... https://logentries.com/doc/java/ As you can see, they support different frameworks. How could I integrate the appenders written by "LogEntries" with your framework?

Other examples: https://github.com/qos-ch/logback-extensions/wiki/Loggly

thanks
Marcello

**Comment by timboudreau** [comment]
Implement [LogWriter](https://github.com/timboudreau/bunyan-java/blob/master/bunyan-java/src/main/java/com/mastfrog/bunyan/LogWriter.java) and bind it with Guice.

I am wondering, though, if I should make public the [LogSink](https://github.com/timboudreau/bunyan-java/blob/master/bunyan-java/src/main/java/com/mastfrog/bunyan/LogSink.java) class, which can receive a `LogLevel` and a `Map<String,Object>`, which would provide a way to do something with the log record before it is converted to a String.  Would that work better for your use-case?

One interesting option for remote logging would be to use something like [Scamper](https://github.com/timboudreau/scamper) to serialize the log record to BSON and ship it over the wire to a remote process (and SCTP will take care of failover, load balancing and finding the log server with the shortest network path).

**Comment by timboudreau** [comment]
FYI, I just made `LogSink` an interface w/ default implementation in 1.6.3, so if you want objects, bind your own implementation of that and ignore `LogWriter`.

**Comment by marcellodesales** [comment]
@timboudreau Thanks for that... The interface makes more sense! 

Do you have a concrete example for that? What I would think is that we could maybe use the same strategy of other frameworks in terms of Appenders... What do you think? That way, we could reuse any appender from them without the need to rewrite anything...

**Comment by timboudreau** [comment]
I think you could write little libraries that each implement an appender
for one or another logging framework.  You wouldn't want to put those
directly in bunyan-java, or anyone using any of them will wind up having a
dependency on all of them.

On Wed, Sep 2, 2015 at 5:25 PM, Marcello de Sales notifications@github.com
wrote:

> @timboudreau https://github.com/timboudreau Thanks for that... The
> interface makes more sense!
> 
> Do you have a concrete example for that? What I would think is that we
> could maybe use the same strategy of other frameworks in terms of
> Appenders... What do you think? That way, we could reuse any appender from
> them without the need to rewrite anything...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/timboudreau/bunyan-java/issues/1#issuecomment-137249020
> .

## 

http://timboudreau.com

**Comment by timboudreau** [comment]
I'll probably get that SCTP logging example I was kicking around the idea of implemented sometime too.  That won't be talking to another logging framework, just shoveling BSON packets over the wire to a back end server, so I don't know that it will help for integrating with other frameworks, but it will be an example of alternate implementations of LogSink.

**Comment by marcellodesales** [comment]
Well, I would think that if you write something that uses the existing Appenders, people would need to require the existing appenders and you would just need to write the Interface to talk to those general appenders... That way, we could reuse existing stuff...

**Comment by timboudreau** [comment]
Perhaps I misunderstood - I thought you were asking for implementations of
interfaces from a bunch of libraries (that bunyan-java would have to depend
on), inside of bunyan-java.

That's fine as a small libraries that adapts bunyan-java to those others,
but it shouldn't be inside bunyan-java or we force every user to drag
around dependencies on logging libraries they may not use.

On Fri, Sep 4, 2015 at 11:52 PM, Marcello de Sales <notifications@github.com

> wrote:
> 
> Well, I would think that if you write something that uses the existing
> Appenders, people would need to require the existing appenders and you
> would just need to write the Interface to talk to those general
> appenders... That way, we could reuse existing stuff...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/timboudreau/bunyan-java/issues/1#issuecomment-137903468
> .

## 

http://timboudreau.com

**Comment by marcellodesales** [comment]
:D Of course not!!! :D 

I'm looking for something like http://www.slf4j.org/... Since it is a façade to other frameworks, it guarantees that all of them can be replaced... Similar to that, users will depend on the following:
- bunyan-java
- bunyan-connector
- logback: http://logback.qos.ch/manual/appenders.html

I can think that bunyan-connector has the abstract implementation of the LogSink taking the log event to be published to whatever appender is configured.

Similar to supporting Log4j2...
- bunyan-java
- bunyan-connector
- log4j2: https://logging.apache.org/log4j/2.x/manual/appenders.html

**Comment by marcellodesales** [comment]
@timboudreau Any plans on this? Or should we keep it close?
